/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsuariosRouteImport } from './routes/usuarios'
import { Route as LivrosRouteImport } from './routes/livros'
import { Route as EditorasRouteImport } from './routes/editoras'
import { Route as AutoresRouteImport } from './routes/autores'
import { Route as IndexRouteImport } from './routes/index'

const UsuariosRoute = UsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)
const LivrosRoute = LivrosRouteImport.update({
  id: '/livros',
  path: '/livros',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorasRoute = EditorasRouteImport.update({
  id: '/editoras',
  path: '/editoras',
  getParentRoute: () => rootRouteImport,
} as any)
const AutoresRoute = AutoresRouteImport.update({
  id: '/autores',
  path: '/autores',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/autores': typeof AutoresRoute
  '/editoras': typeof EditorasRoute
  '/livros': typeof LivrosRoute
  '/usuarios': typeof UsuariosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/autores': typeof AutoresRoute
  '/editoras': typeof EditorasRoute
  '/livros': typeof LivrosRoute
  '/usuarios': typeof UsuariosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/autores': typeof AutoresRoute
  '/editoras': typeof EditorasRoute
  '/livros': typeof LivrosRoute
  '/usuarios': typeof UsuariosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/autores' | '/editoras' | '/livros' | '/usuarios'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/autores' | '/editoras' | '/livros' | '/usuarios'
  id: '__root__' | '/' | '/autores' | '/editoras' | '/livros' | '/usuarios'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AutoresRoute: typeof AutoresRoute
  EditorasRoute: typeof EditorasRoute
  LivrosRoute: typeof LivrosRoute
  UsuariosRoute: typeof UsuariosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/usuarios': {
      id: '/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof UsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/livros': {
      id: '/livros'
      path: '/livros'
      fullPath: '/livros'
      preLoaderRoute: typeof LivrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editoras': {
      id: '/editoras'
      path: '/editoras'
      fullPath: '/editoras'
      preLoaderRoute: typeof EditorasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/autores': {
      id: '/autores'
      path: '/autores'
      fullPath: '/autores'
      preLoaderRoute: typeof AutoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AutoresRoute: AutoresRoute,
  EditorasRoute: EditorasRoute,
  LivrosRoute: LivrosRoute,
  UsuariosRoute: UsuariosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
